### ISSUE TITLE
Del variable from dataset causes handles to become invalid

### ISSUE THREAD

**Issue by DavidFair** [scipp/scipp#1176]
I've just been caught out / surprised a bit by the following reproducer:
``` python
import scipp as sc

d = sc.Dataset()
d["a"] = sc.Variable([1.0, 2.0, 3.0])
d["ref"] = sc.Variable([1.0, 1.0, 1.0])

reference = d["ref"]
del d["ref"]

# Will segmentation fault
d /= reference
```

As a developer I can clearly see that we delete the variable that the dataset is holding.

This is a deviation from expected behaviour as per Python [specification](https://docs.python.org/3/reference/simple_stmts.html#the-del-statement) where we it should:
> Deletion of a name removes the **binding** of that name from the local or global namespace, depending on whether the name occurs in a global statement in the same code block.

This should not be garbage collected since `reference` in the above reproducer still holds is bound to the underlying variable. I can see users being caught out by this since `del` is the obvious way to remove something from a dataset.

What makes this worse is that Jupyter Notebooks will not forward on the segmentation fault, users will either have to pay attention to their console output (or Kernel log if it's not available in the case of some IDEs)

**Comment by SimonHeybrock** [comment]
I see the problem, but I am not sure it is fixable without a fundamental paradigm shift. It would not be so much of a problem if `d['ref']` was just referring to a variable, but it actually also links to all coordinates, masks, and attributes. To implement what you ask for we would need to add shared pointers to `Variable` and introduce a shared ownership model. Apart from possible performance issues, this also makes multi-threading a headache, since it might mean we also need to add locks.

In most Python bindings we are actually bypassing this by using pybind's "keep-alive" mechanism, so we are essentially having somthing like shared pointers here. In the case of *items* of a dataset though we canot do this, because a dataset is *not* a dict of data arrays --- the alignment of coords means that all items share the coords, i.e., there is just a single copy.

@OwenArnold @nvaytet What are your thoughts on this?

**Comment by rozyczko** [comment]
Or maybe just make assignment do a deep copy by default instead?
I would expect `Dataset` to behave similar to what python `dict` does.

```
d = {}
d["a"] = sc.Variable([1.0])
d["b"] = sc.Variable([1.0])
ref = d["b"]
del d["b"]
ref
  <scipp.Variable>          PyObject   [dimensionless]  ()  [<PyObject>]
```

**Comment by SimonHeybrock** [comment]
@rozyczko I don't think assignment is an operation that can do that in Python? `=` is just binding a name to what is on the right-hand side? Or is there?

**Comment by rozyczko** [comment]
No, there isn't.
`copy.deepcopy` would be a way to avoid the issue but as you said this morning, it would be too expensive.

**Comment by SimonHeybrock** [comment]
Also, it would prevent modifications of dataset items.

**Comment by SimonHeybrock** [comment]
Considering our options here, in the context of the likely refactor of coord handling we will do (based on #1155 but different). Boundary conditions:

- No `shared_ptr` in `Variable`.
- No `shared_ptr` in `Variable(Const)View` or `DataArray(Const)View`.

The above are requirements to maintain efficient slicing and dataset item selection. The places where this is relevant are `groupby` and functionality related to `realign` (which relies on `groupby`).

- `shared_ptr` in `DataArray` *may* be acceptable, provided that it does not cause slowdown in `histogram_md_recurse` used for realign functionality.
- `shared_ptr` in `Dataset` likely acceptable.

Note that the bug described in the original report should also affect, e.g., references to coords, if the coord gets deleted. That is, we would need sharing of individual coords (and masks, and attrs) as well as sharing of data arrays within dataset.

In any case, sharing *outside* the scope of a dataset has to be avoided, since it would likely cause many headaches (and we do not want to go the copy-on-write route).

To fix the actual issue, we would then need to handle `__getitem__` differently on the Python side: Instead of returning a non-owning `VariableView` (in case of coords) or `DataArrayView` (in case of dataset items), we would need to return a different object that increases the reference count for the variable (in case of coords) or the data array (in case of items in a dataset). All this while avoiding fallback to the behavior of Python dicts that *share* their items. This is difficult, because we "want" the reference to the deleted dataset item to behave like a data array, but at the same time it still references the original coords.

So maybe there is a better way... can we just "detect" when an item is deleted and raise an error? This would require keeping some sort of "view list", such that `del` can update the views?

**Comment by SimonHeybrock** [comment]
Here is another solution, which might mostly leave our C++ data structures intact, and has the advantage of *invaliding* views, instead of attempting to retrofit a shared ownership model which had been deliberately avoided. Draft/sketch:

```python
import scipp as sc

class Dataset(sc.Dataset):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._views = []
        
    def __getitem__(self, name):
        item = DataArrayView(super().__getitem__(name))
        self._views.append(item)
        return item
    
    def __delitem__(self, name):
        for item in self._views:
            item._valid = False
        self._views = []
        super().__delitem__(name)
    
    def __add__(self, array):
        return super().__add__(array.access())


class DataArrayView(sc.DataArrayView):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._valid = True

    def access(self):
        if not self._valid:
            raise RuntimeError("DataArray view invalidated by insertion or deletion in Dataset. "
                               "Use copy() to extract DataArray from view before modifying Dataset, "
                               "or get item again after modification.")
        return self

d = Dataset({
    'a':sc.Variable(['x'], values=[1.0, 2.0, 3.0]),
    'ref':sc.Variable(['x'], values=[1.0, 1.0, 1.0])})
ref = d['ref']
d + ref
del d['ref']
d + ref
```

Add this line to make the example work (temporary, see notes):
```diff
diff --git a/python/dataset.cpp b/python/dataset.cpp
index f06b440e..07323ed3 100644
--- a/python/dataset.cpp
+++ b/python/dataset.cpp
@@ -340,6 +340,7 @@ void init_dataset(py::module &m) {
         View for DataArray, representing a sliced view onto a DataArray, or an item of a Dataset;
         Mostly equivalent to DataArray, see there for details.)");
   dataArrayView.def(py::init<DataArray &>());
+  dataArrayView.def(py::init<DataArrayView &>());
 
   bind_data_array_properties(dataArray);
   bind_data_array_properties(dataArrayView);
```

Essentially we wrap `Dataset` so it can keep track of their views (and their coord, mask, and attr views, not shown here, so also `DataArray` needs to be wrapped). All functions returning data arrays or datasets have to be wrapped (but we were planning to investigate this anyway, for improved error messages and "overload" handling).

Further notes:
- Not just `__delitem__` is affected, also `__setitem__` since it may lead to `Dataset` moving variables around within in `std::unordered_map`. Since we are not storing pointers the address may change and we should be able to trigger the segfault reported originally also there.
- All the other set-like objects are also affected, i.e., `Dataset`, and the coord-, mask-, and attr-views. There are no owning versions of the latter three, the view tracking has to happend in `Dataset` and `DataArray`.
- Wrapper for `DataArrayView` (and `VariableView` in case of coords, ...) should not be required, we can probably simply add a binding for a method to invalidate the view by setting its held pointer to `nullptr` on the C++ binding side.

@OwenArnold @nvaytet @rozyczko Have a look at this new approach. Is there any flaw? The GIL should protect us from things going wrong here, but please double check the logic. Any other problems/drawbacks you can think of?

**Comment by rozyczko** [comment]
Wrapping the access in Python seems a good idea but I am not sure why you're deleting
`_valid` flags for all the items on a single item removal. I would maybe suggest using a `dict` here:

```python
class Dataset(sc.Dataset):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._views = {}
        
    def __getitem__(self, name):
        item = DataArrayView(super().__getitem__(name))
        self._views[name] = item
        return item
    
    def __delitem__(self, name):
        item = self._views[name]
        item._valid = False
        del self._views[name]
        super().__delitem__(name)
    
    def __add__(self, array):
        return super().__add__(array.access())
```

**Comment by SimonHeybrock** [comment]
> I am not sure why you're deleting `_valid` flags for all the items on a single item removal

`Dataset` is storing items in an `std::unordered_map`. If reshaing occurs (from interstion or deletion) *all* iterators are invalided, not just the changed one. Similar issues would occur also if we used different containers. This could be avoided by storing *pointers* in the map, but does not really seem worth the effort and overhead, since views should be treated as short-lived and we do not want to encourage users to store them long-term.

**Comment by SimonHeybrock** [comment]
The reiterate: This problem is not just with deletion, but also insertion invalides all views.

**Comment by nvaytet** [comment]
I think wrapping seems like a nice and non-invasive solution.
Iterating through the list of views may become a problem if you have many many views, but in practise i don't see this ever being a problem.
I think having an error message instead of a seg fault is definitely a big plus.
