### ISSUE TITLE
Organization of code and components depending on (but not part of) scipp

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1220]
1. https://github.com/scipp/ess is a bucket full of neutron-related code, with no organization. We have
   - Things to triage for inclusion in `scipp`.
   - Things to triage for inclusion in `scipp.neutron`
   - Technique-specific code.
   - Instrument-specific code.
   - Facility-specific code?
2. A couple of examples of functionality that should *not* be part of `scipp-neutron`, in particular `convert_with_calibration` and `load_calibration`. These appear to be to specialized to a specific data format to justify inclusion in `scipp.neutron` itself, violating our [scope guidelines](https://scipp.github.io/about/contributing.html#scope).
3. [Dockerfile](https://github.com/scipp/scipp/blob/master/scipp-jupyter-demo.Dockerfile) is neutron-specific and even pulls in Mantid, i.e., it does not belong here. We may want multiple different images for different purposes. Should there be a single repo for individual cases? One for a collection of demos and tutorials?
4. How do repositories relate to packages?
   - Should there be one repository per Python package?
   - Is it ok to have multiple Python packages form one repository?
   - Is it ok to have code/notebooks that are *not* in the package in the same repo as the code for the package?
   - What are good package scopes? `pip install ess-data-reduction` then `from ess import loki`? `pip install ess-loki`

How should this be organized? Is, e.g., the SANS code facility specific? When can we claim that it is not? That is should there be `ess-sans` as a module? Or just `ess-loki`? Could/should all generic SANS code live in `scipp.neutron.sans`?

**Comment by nvaytet** [comment]
I would say that instrument specific code (e.g. a reduction worflow/notebook) should go in `ess-loki`.
Generic SANS functions, that are used by more than one instrument should go in `scipp.neutron.sans` *only* if they are doing things that other `scipp` or `scipp.neutron` functions are not doing.
On the other hand, if a function is used by more than one instrument, but is basically just calling several different `scipp` functions one after the other, it should go in `ess-sans`.

I don't know if we want to have `ess.sans` and `ess.sans.loki` or `ess.loki`?

**Comment by nvaytet** [comment]
I guess there is a futher discussion to have on how we organise `scipp` itself.
Should `scipp.neutron` live in `scipp` or should it be a separate repo? What about `scipp.plot`?
Looking at, for example, project Jupyter, their main package `jupyter` is just a meta-package that pulls in various components.
They then have `jupyter_core` which is their core library (would probably be the equivalent of our `scipp` minus the `neutron` and `plot` parts).
Other repos (`notebook`) then depend on core to run.

If we truly intend for `scipp` to be used by other communities than the neutron sciences, it would be nice to separate the currently deeply embedded neutrons bits (including the units).

We could have these repos (and corresponding conda packages):
- `scipp_core`: the current `scipp` minus `neutron` and `plot`. The most low-level building block (not to be confused with the current `scipp.core`: `scipp_core` would be `scipp.core + scipp.variable + scipp.dataset + scipp.units...`)
- `scipp_plot`: the current `scipp.plot` (would ideally not depend on `scipp.core` and only rely on the conversion of `scipp` objects to python `dicts` (via a `to_dict` converter).
- `scipp_neutron`: the current `scipp.neutron`. Installing the conda package would pull in packages `scipp_core` and `scipp_plot`)
- `scipp`: could pull in for example `scipp_core` and `scipp_plot` in order to provide a generic package useable in a notebook.

I then have no idea how one would organise CI for such a setup. If each repo has its own separate CI, we will surely have problems with changes in one repo breaking other repos. I guess if you need changes in a higher-level repo that also require changes in `scipp_core`, you have to first make the changes in `scipp_core`. This should be ok?

On project Jupyter, the core seems to have very little CI testing in it, so I am not sure how they keep everything working together.
I looked around a little, and it seems one way to do this is that every PR in one repo triggers CI jobs that build all the other repos as well, and runs both the current repo's tests and all the tests in the other repos as well. While this may sound like a lot, it might not take much longer than what we are doing now. We are testing every part one after the other.

For a new change in `scipp_neutron` you would pull the latest `master` from `scipp_core` and run the tests for that. You would then pull the latest `scipp_plot` and so on. And finally, you would run the tests on `scipp_neutron`, using the freshly built `scipp_core` as the core.

If you are making changes to `scipp_core`, you have to ensure you are not breaking something for higher level modules, so you have to run all the CI one after the other also.

Sometimes you need to make changes to both `neutron` and `core`. As mentioned above, if for example you need to add a new operation in `core` (let's say we want to add `exp`), so you can use it in `neutron`, it should be fine to first make the changes in `core` and then put additions in `neutron`.

If you are removing a functionality, remove it first in `neutron` before removing it in `core`.

However, if you are making an API-breaking change in `core`, it is not so clear to me how to proceed. Say I want to rename `exp()` to `exponential()`, and I have code in `neutron` that uses `exp`. If I make the change in `core` first, the CI will never pass because the tests in `neutron` will fail, and I cannot make the changes in `neutron` first for the same reasons. I see two options:
- we could either just forcibly merge these API changes, once we understand that all the test failures are accounted for by this change of API
- we could provide both APIs in `core` for a while (maybe with a deprecation warning) in order to get the CI to pass, then make the changes in `neutron`. In a second step, remove the deprecated version in `core`.

**Comment by wpotrzebowski** [comment]
SasView is also going towards different repositories for gui, core (sascalc) and models (sasmodels), so I think if we have corresponding structure across dmsc it may be useful. This may particularly help in cases like running headless-only, so we know which repos we need to pull from and can provide minimum dependencies.

**Comment by OwenArnold** [comment]
As @nvaytet says: ```Sometimes you need to make changes to both neutron and core. As mentioned above, if for example you need to add a new operation in core (let's say we want to add exp), so you can use it in neutron, it should be fine to first make the changes in core and then put additions in neutron.``` This is a good example to think though and in particular how this can be done rapidly for users at an experiment, or if you think back to our V20 experiments where there is limited time and different levels of the solution stack are affected by the fix.

Other considerations that come to mind:
- Handling an unstable scipp API as we current do seems particularly hard given that we will break things downstream more frequently.
- Follow on from point above, how to pin/version dependencies in a reliable way. Maybe when you update downstream packages always set minimum version of dependencies or similar?
- Problem for cron-job based CI across projects, who is responsible for investigating and making fixes when it is more difficult to spot problems at time of inception (this was one driver for Mantid System Tests moving into the main Manid repo)
- Even though functions may sensibly be located in one layer, we need to ensure that they can be imported from anywhere. For example, we might locate `mean_filter` in `scipp.neutron.ess.imaging`, but if someone wants to use that to correct a 2D detector for a reflectometry experiment, they should be able to easily import it. i.e. we should NOT suppose that once we get to the technique level of a package structure that modules from other technique areas will not be used.
- Who takes responsibility for each repo/package/layer? How does coordination work? The science teams will often find they are reusing/copying the same routines, but I think DRAM should be the ultimate owners to ensure that standards/testing/documentation are provisioned properly. So how do we coordinate/trigger this - is the in the remit of the data-scientist?
- What about Facility/Technique/Instrument specifics that really need to be in c++ these would not all fit happily into scipp.neutron. How could we build package and distribute those? Would we implement those completely independent c++ projects binding to scipp only via python?
- Note scipp/neutron is not optional at CMake time but could be made to be and CI could follow. Would it help keep some things in one repository, but easily disable from the build system at cmake time? i.e. Why apply flexibility that is inconvenient to us in our current state and costly to our sponsors?

**Comment by SimonHeybrock** [comment]
Notes from discussion:
- Downstream projects should run frequent tests agains scipp HEAD, but *depend* on released versions.
- Medium term: separate `scipp.neutron` from `scipp`, since it does not belong there (just like the is no `numpy.climate`).
- Do *not* have `neutron.sans` as well as `ess.sans` (having `sans` twice would be confusing). Instead:
  - `neutron.sans`
  - `ess.loki`

**Comment by OwenArnold** [comment]
Additional notes

* notebooks `ess-notebooks` should live in separate repo from ess and neutron tools
* use conda for distribution not pip

**Comment by SimonHeybrock** [comment]
> use conda for distribution not pip

@OwenArnold @DanNixon One thing to consider here: On OSX we make our own package scipp/Mantid (not using conda), so having a pip package may be useful there?

**Comment by DanNixon** [comment]
I don't think we should do anything different on a per OS bases unless there is a good reason.

**Comment by SimonHeybrock** [comment]
See new projects in https://github.com/scipp.
