### ISSUE TITLE
Strange rendering from Instrument_view

### ISSUE THREAD

**Issue by celinedurniak** [scipp/scipp#1227]
Using an event file from WISH,` instrument_view` displays an additional vertical ring and detectors in the horizontal plane seem to be missing.
See screenshot generated using `bins=1 `and `rendering=Fast` in `instrument_view`

![Screenshot from 2020-06-29 08-46-56](https://user-images.githubusercontent.com/7889724/85983440-d2984580-b9e7-11ea-93e8-fad25f4834ce.png)

Note: Since the input file is quite large, I usually use `FilterByTofMin=6000` and  `FilterByTofMax=20000` when loading the data

**Comment by nvaytet** [comment]
It's weird, i can't seem to reproduce the behaviour:
![Screenshot_2020-07-07_15-18-44](https://user-images.githubusercontent.com/39047984/86787369-4cbe6f00-c065-11ea-8a42-c843d0eff302.png)

**Comment by nvaytet** [comment]
@celinedurniak could you tell us if this is still happening since we made a major update to the instrument view in #1243 ?
thanks

**Comment by celinedurniak** [comment]
@nvaytet I just checked using a conda environment (scipp version 0.4.0-456). 
It works (see enclosed screenshot). Thanks.

<img width="1343" alt="Screen Shot 2020-08-20 at 14 31 16" src="https://user-images.githubusercontent.com/7889724/90770396-0578fe80-e2f2-11ea-8dce-fc7b6ffedb5f.png">

**Comment by nvaytet** [comment]
This doesn't seem to be fixed, as it still happens when using `sc.load(..., advanced_geometry=True)`
This must happen in the Mantid converter, probably a singularity when `y = 0` which is not properly handled?
![Screenshot at 2020-08-27 17-00-18](https://user-images.githubusercontent.com/39047984/91459607-1e9c2500-e887-11ea-8de3-64e9f87f35dd.png)
