### ISSUE TITLE
Profile plot key displays floating point instead of integer keys

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1369]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/12912489/98116563-be3deb00-1ea8-11eb-84c4-5be08d707491.png">

I suppose this happens because internally things are converted to float before plotting the 2d plot. Can we detect when original coords are integral and convert back?

**Comment by nvaytet** [comment]
I guess we could do this.
Right now, I would say this might become a little messy.
The label is actually updated on every mouse movement so that when we click we simply duplicate the current line (and this also duplicates its label). So we would also have to change this to avoid losing too much performance.

On the plot above, where the numbers are lying is a little confusing. The first straw lies from coordinate `'straw'` 0 to 1. Would an offset by 0.5 make more sense? i.e. the first straw would be centered on straw 0 (or 1)?

**Comment by SimonHeybrock** [comment]
I don't think adding an offset would help.
