### ISSUE TITLE
Plotting certain data without coords does not work

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1457]
See https://github.com/scipp/scipp/pull/1456#pullrequestreview-548874561.

Note that the same issue was probably fixed before?

**Comment by nvaytet** [comment]
So i have a mwe here
```Py
data = sc.DataArray(data=sc.Variable(
    dims=['pack', 'tube', 'straw', 'pixel'],
    values=np.random.rand(2, 8, 7, 256)),
                    coords={})
a = np.sin(np.linspace(0, 3.14, num=256))
data += sc.Variable(dims=['pixel'], values=a)
data.masks['tube_ends'] = sc.Variable(dims=['pixel'],
                                      values=np.where(
                                          a > 0.5, True, False))
plot(data, axes={'y': 'tube'})
```
and the issue seems to be when specifying the axes. Without `axes={'y': 'tube'}`, the plot works fine.

When trying to place dimensions along axes, it is looking for `'tube'` in the coords of the original data array, and of course there is no coord tube, as it gets automatically added afterwards as a dummy coordinate in `model.py`.

So we need to check inside the dims also? Or maybe set the axes once the dummy coords have been added?
