### ISSUE TITLE
The method ".bin" seems to have disappeared in version 0.4.0

### ISSUE THREAD

**Issue by fott** [scipp/scipp#1504]
The method ".bin" for event data seems to have disappeared in version 0.4.0

>>binned = sc.bin(SpotsSC, [ybins, xbins])
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'scipp' has no attribute 'bin'

**Comment by fott** [comment]
The method ".bin" is available in the dev. version 0.4.0_1869
(The documentation is ahead of the versions :-)

**Comment by nvaytet** [comment]
Thanks for the feedback.

Yes the documentation is indeed relevant to the development branch of `scipp`.
However, you can find the documentation for previous releases by changing the url in your browser to https://scipp.github.io/release/0.4.0/ (for 0.4).

In the future, we will make this more obvious on the documentation pages, and visitors will by default land on the latest release documentation instead of the development pages.
