### ISSUE TITLE
sc.sum is 5x-20x slower than numpy

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#1517]
![Screenshot at 2021-01-08 15-22-01](https://user-images.githubusercontent.com/39047984/104027122-3dacab00-51c7-11eb-936e-b8721f49d166.png)

Summing over the `z` dimension yields 566 ms, 5x slower than numpy's 106 ms

**Comment by SimonHeybrock** [comment]
Note:
- Reduction operations operations are not multi-threaded at this point.
- #1486 may bring an improvement, especially because of the lack of multi-threading.

**Comment by SimonHeybrock** [comment]
With #1486 it seems summing the inner dim is now much faster (I get 175ms instead of numpy's 125ms).

Summing the *outer* dim is still slow though. I believe the problem here is likely the iteration order chosen by `transform` which could be easy to fix in theory (but we'd need to ensure it does not cause pessimization for other cases).
