### ISSUE TITLE
Plotting or Rebin bug with thickness

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1559]
1. Run the following in a notebook
```python
import scipp as sc
import numpy as np
x = sc.Variable(['x', 'y', 'z'], values=np.ones((10, 10, 10)))
sc.plot.plot(x)
```
2. Then increase thickness
3. Then hit rescale - No change in colour scale 

implies doesn’t seem to be summing as I increase thickness as set rescale. Can you check?

**Comment by OwenArnold** [comment]
@nvaytet FYI

**Comment by SimonHeybrock** [comment]
I believe this is not a bug, but a feature. Compare:

```python
import scipp as sc
import numpy as np
x = sc.Variable(['x', 'y', 'z'], values=np.ones((10, 10, 10)), unit=sc.units.counts)
sc.plot.plot(x)
```

Your exampe has `unit=sc.units.dimensionless`, which plotting treats similar to other units such as `sc.units.K`. The mechanism is:

1. Counts are *summed* during the resampling process.
2. For any other unit, the *mean* is used, since summing, e.g., temperatures does not yield a meaningful result.

So the only question is whether it is correct that we put dimensionless quantities into category 2.

**Comment by OwenArnold** [comment]
Would it be better to have explicitly controllable behaviour here in the plot rather than basing on units?

**Comment by SimonHeybrock** [comment]
> Would it be better to have explicitly controllable behaviour here in the plot rather than basing on units?

Feels odd to introduce such a mechanism just for a single unit. In all other cases control would lead to nonsensical results.

**Comment by OwenArnold** [comment]
Document current behaviour. I'm modifying the visualisation docs anyway so I'll do it there.

**Comment by SimonHeybrock** [comment]
Documented in #1554. Since we could not come up with an example where dimensionless shoul be treated like counts (summed) I will close until we run into actual problematic case.
