### ISSUE TITLE
Broadcast with slices

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1606]
Writing to slices does not broadcast:
```.py
v = sc.Variable(['x'], values=[1,2,3])
v['x', 1:3] = 0*sc.units.one
```
```
RuntimeError: {{x, 2}} expected to be equal to {}
```
or
```.py
v = sc.Variable(dims=['x', 'y'], values=np.array([[1,2,3], [4,5,6], [7,8,9]]))
v['x', 1:3] = sc.array(dims=['x'], values=[0, 0])
```
```
RuntimeError: {{x, 2}, {y, 3}} expected to be equal to {{x, 2}}
```

The former is allowed in numpy, while the latter only works when slicing the last dimension:
```.py
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a[..., 1:3] = np.array([0,0])
```

We should support this at least to the extent that numpy does. Given the more powerful broadcasting elsewhere and that we don't really use dimension orders, we should probably support this fully.

**Comment by SimonHeybrock** [comment]
I agree, and I can't remember why this was not supported since the beginning. On the C++ side this would map to `VariableView::assign`, which would be fixed to support broadcasting.

I think there is probably a different but related issue when assigning with a different dtype. We should also allow (certain) type conversions here.
