### ISSUE TITLE
Unexpected result from length multiplication

### ISSUE THREAD

**Issue by arm61** [scipp/scipp#1644]
Multiplying a `sc.Variable` with unit of `sc.units.mm` by one of unit `sc.units.angstrom` through a surprising error. 

```
import scipp as sc

a = 1. * sc.units.mm
b = 2e7 * sc.units.angstrom
a * b

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-71-1faaf5db72d6> in <module>()
      3 a = 1. * sc.units.mm
      4 b = 2e7 * sc.units.angstrom
----> 5 a * b

RuntimeError: Unsupported unit as result of multiplication: (mm) * (Å)
```

Would have expected these to work together.

**Comment by jl-wynen** [comment]
This is a general issue with the current units implementation. All units must be defined when compiling the library because we are using boost::unit under the hood. And mm*Å is just not included at the moment.

We are looking into changing it to a more flexible approach: #1620
But in the meantime, if you need this unit, you will have to configure scipp manually in order to use it: https://scipp.github.io/developer/customizing.html#units-systems

**Comment by SimonHeybrock** [comment]
@arm61 Since #1620 will take a while to resolve, we can add support for this unit conversion manually. Can you think of any other combinations you require?

**Comment by arm61** [comment]
That's the only one I have encountered thus far. If you add this one manually, I can look at the diff and do it myself in future 🙂

**Comment by jl-wynen** [comment]
Lazy answer: #1650

**Comment by arm61** [comment]
Sick. I think I an manage that. Let me build a dev build on my laptop and then I can sort and make a PR.

**Comment by nvaytet** [comment]
That might not be the full answer depending on what @arm61 is expecting.
Are you expecting `a * b` to give `2e7 AA * mm` or are you expecting to get `2e7 mm^2` (i.e. automatically recognise that `mm` and `AA` are both units of length and do the conversion on the fly).
Because the linked PR would only give you the first one.

We do not do automatic conversions. E.g.
`(1.0*sc.units.mm) + (2.0*sc.units.m)` fails saying it can't add `m` and `mm`.

**Comment by arm61** [comment]
Okay this is good to know. So currently, I should try and just be consistent with my units from the start?

**Comment by SimonHeybrock** [comment]
I think it is fine to have Angstrom in addition to, e.g., `m`, since this actually shows up in unit conversions, e.g., to wavelength. This ialso the reason why we have `m * AA / us` as a supported unit, and certain other combinations.

Can you work around you issue by working with `m` instead of `mm`, and doing operations in a different order, or wait until we merge a change to support `m * AA`?

**Comment by arm61** [comment]
I think I can work round the issue pretty easily. Don't worry about the `mm * AA`.

**Comment by nvaytet** [comment]
However, maybe we could support **manual** conversion, such as `a.to(sc.units.angstrom)` or something, which forces the user to know when they are converting and makes the code readable?

**Comment by SimonHeybrock** [comment]
> However, maybe we could support **manual** conversion, such as `a.to(sc.units.angstrom)` or something, which forces the user to know when they are converting and makes the code readable?

This is definitely planned, but I think we may want to wait until we have decided on a better way to implement units, since in particular the way unit scales are handled may affect the implementation.
