### ISSUE TITLE
Missing datetime operations

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1768]
- [x] Unit conversions: `sc.scalar(value=np.datetime64('2004'))`
- [ ] dtype conversion: `sc.scalar(value=1000, unit=sc.units.s).astype(sc.dtype.datetime64)`
- [x] HDF5 I/O (see #1780)

**Comment by SimonHeybrock** [comment]
Should the second on actually be supported? Strictly speaking it is not really a pure `dtype` conversion, but kind of reinterpreting the values based on assumed knowledge of what epoch is. Shouldn't we rather use `epoch + 1000 * sc.units.s`?

**Comment by jl-wynen** [comment]
Strictly speaking, this is true. But the dtype cast could improve performance when reading / writing files because you can omit extra copies. Unless `h5py` has native support for `np.datetime64`?

@OwenArnold You found this, do you have a good use case that needs the cast?

**Comment by OwenArnold** [comment]
Aside from mantid->scipp time conversions for logs, we also potentially have the following requirements for neutron scattering:

* Convert sample-environment times, which maybe recorded as an offset since the start of the run to a datetime
* Convert to "time at sample" for filtering. This is effectively a time difference subtraction from a datetime to give another datetime.

I agree with Simon's statement that the `astype` is really doing a "reinterpreting the values based on assumed knowledge of what epoch is", so misleading.

Supporting offsets such as  `epoch + 1000 * sc.units.s` is better I think.

**Comment by SimonHeybrock** [comment]
@OwenArnold This is supported already.

**Comment by jl-wynen** [comment]
Point 1 as written is implemented by #1801
Branch `datetime-ctor-conversions` adds support for conversions in constructors of `Variable` and `Variable.value` (only scalar).
Holding off on a PR until the ownership changes are merged.

**Comment by SimonHeybrock** [comment]
2 out of 3 done, and the remaining one is controversial and likely not required right now. -> closing.
