### ISSUE TITLE
Physical constants

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2064]
With #2058 implementing custom coordinate transformations will become possible. For this (and other) reasons, having a library of physical constants as part of scipp would be important.

**Comment by jl-wynen** [comment]
Taking a quick look into this. There is a conceptual issue. We should store constants with their unit in order to avoid errors. But in scipp this means storing a Variable which implies an allocation and is only possible in the `variable` module or above.

- We could create a custom type for number-with-unit or use `llnl::units::precise_measurement` directly.  But in order to make this easily usable it would need to be (implicitly) convertible to a scalar Variable.
- Or we provide functions which create Variable instances on demand. In Python those could be exposed as properties but in C++ one would still need to use function call syntax.

Which one sounds best? Any better ideas?

**Comment by SimonHeybrock** [comment]
On-demand instances sounds fine. We might even want to have support for loading custom/updated constant tables at some point? There is little use for this *within* scipp, so even if we want it as parts of `scipp.units` (Python) it does not imply that it has to live in `scipp::units` (C++).

**Comment by jl-wynen** [comment]
> There is little use for this within scipp, so even if we want it as parts of scipp.units (Python) it does not imply that it has to live in scipp::units (C++).

True. But unit conversions need it in C++. So it would need to be in a meaningful place. We could of course add a new submodule. But that seems like overkill.

**Comment by SimonHeybrock** [comment]
> > There is little use for this within scipp, so even if we want it as parts of scipp.units (Python) it does not imply that it has to live in scipp::units (C++).
> 
> True. But unit conversions need it in C++. So it would need to be in a meaningful place. We could of course add a new submodule. But that seems like overkill.

You refer to the C++ function implementing pieces of transforms in `scippneutron`? In principle those could be passed from Python, so not necessarily?

**Comment by jl-wynen** [comment]
> You refer to the C++ function implementing pieces of transforms in scippneutron?

Yes.

If we put the constants into Python only, we could use scipy instead of LLNL/units.
