### ISSUE TITLE
Can't pip or conda install on osx arm64

### ISSUE THREAD

**Issue by RBrearton** [scipp/scipp#2483]
Hi there,

Issue as stated in the title. I've added scipp to my conda channels. Steps to reproduce:

### Using [installation](https://scipp.github.io/getting-started/installation.html) guide

`conda create -n env_with_scipp -c conda-forge -c scipp scipp`
Gives:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:
  - scipp

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/scipp/osx-arm64
  - https://conda.anaconda.org/scipp/noarch
...etc

### Using pip
Note the issue is agnostic of python version; chosen 3.8 for simplicity.
`conda create --name scipp python=3.8`
`conda activate scipp`
`pip install scipp`

Gives:

ERROR: scipp from https://files.pythonhosted.org/packages/07/44/9d6f523146a2c4c651d33679bb2b123527463f5e85bcb1c72571206aedfa/scipp-0.12.3.tar.gz#sha256=f69b8d63d022c9b72f587afdc4637d46298d3ef0702388c4b5560f2016e59673 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

I figured I could just download that tar.gz, add the setup.py from your github repo, manually install tbb-devel and run `pip install .`. This works, but gives me:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/easy/lib/python3.8/site-packages/scipp/__init__.py", line 24, in <module>
    from .core import __version__
  File "/opt/homebrew/Caskroom/miniforge/base/envs/easy/lib/python3.8/site-packages/scipp/core/__init__.py", line 6, in <module>
    from .._scipp import _debug_
ModuleNotFoundError: No module named 'scipp._scipp'

When I try to import scipp. I could keep chasing, but I guess that you're just lacking an osx-arm64 build (a colleague was able to pip install without issue on an intel mac).

**Comment by SimonHeybrock** [comment]
Hi Richard!
Thanks for reporting this. We are looking into building wheels for Apple Silicon. Will get back to you.

Simon

**Comment by jl-wynen** [comment]
For now, as a workaround, you can install scipp from source as described here: https://scipp.github.io/reference/developer/getting-started.html
I managed to build a working version of scipp in this way. But it would not be installed as a proper Python package. So you have to manage `PYTHONPATH` yourself as shown in the docs (or using `conda develop <isntall-dir>`).

I also tried building with pip. I disabled parallelism by removing `tbb-devel` here https://github.com/scipp/scipp/blob/7bc56d633763247d6a9729958c6e5d62d8f15d27/pyproject.toml#L10
and adding `'-DTHREADING=OFF'` to the list here https://github.com/scipp/scipp/blob/7bc56d633763247d6a9729958c6e5d62d8f15d27/setup.py#L19
With these changes, I managed to install scipp using `pip install .`. (I used pipenv to make an environment instead of conda in this case.)
You could use this instead of the manual build but of course, scipp will be slower because it would not be parallelised.

**Comment by SimonHeybrock** [comment]
@RBrearton We have published a new package (0.12.4) to PyPI that should work on arm64. Note that this is currently *single threaded* since we are still working out some trouble with TBB.

There is also a Python 3.8 conda package for arm64 (with TBB), 3.9 should follow soon.

**Comment by jl-wynen** [comment]
The conda package for Python 3.9 is out now.

**Comment by RBrearton** [comment]
Thanks for this, I can confirm that scipp is working for me after a conda install on python 3.9.10. I suppose I'll leave this open since there's still no multithreading capabilities?

**Comment by jl-wynen** [comment]
Cool!
Yes, leave it open. There no support for building the conda packages on CI yet. The current solution is just a temporary manual fix.

**Comment by SimonHeybrock** [comment]
To keep track of the status:

- [x] PyPI wheel builds (for `pip`) have been automated since scipp-0.13
- [ ] conan builds are still done manually. Will either need to figure out how to cross-compile, or use a self-hosted M1 worker, since Github Workflows do not provide this at this point. Or wait?

**Comment by SimonHeybrock** [comment]
We have since tested the release build with conda build, see https://github.com/scipp/scipp/actions/runs/2343723739. That is, this should be solved.
