### ISSUE TITLE
Units with "eflag", etc.

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2920]
Recent changes limited the flags that can be set in the underlying `llnl::units` library, in particular for saving to HDF5. However, changes such as https://github.com/LLNL/units/pull/265/files#diff-a23d463ea7f7cf9ac2e9b65fca6eaa81bfb5c71b8b59e4cab074488704f46504 show that this was probably a bad idea.

I think we need to go back to storing more flags. See also #2888.

**Comment by jl-wynen** [comment]
Since the encoding of units seems to be quite complicated, I see three options.
- We can store the full state of the `llnl::unit` as in my first draft. This would support all units but makes it harder to migrate to a different library as we would have to understand the encoding at that point.
- Filter like we do now but allow more flags. I suspect that we would end up implementing all flags and other fields eventually.
- Make up our own encoding. This would be the most robust in terms of migrating but also a bunch of work and potentially complicated.

**Comment by jl-wynen** [comment]
Agree. But in 1), an encoding change on their end breaks our format.

**Comment by SimonHeybrock** [comment]
What if we simply store all known flags (not using their encoding)?

**Comment by jl-wynen** [comment]
What do you mean?

**Comment by SimonHeybrock** [comment]
What I mean is, we should consider storing all the (known) field values, instead of, e.g., a byte-wise copy of the units object.

**Comment by jl-wynen** [comment]
So like my initial implementation that stored `eflag`, `iflag`, `commodity`, etc as individual items?

By all known, do you mean, look at the C++ class and store all attributes. Or only store what we know what it means?

**Comment by SimonHeybrock** [comment]
I suppose I mean all documented ones? The "unknown" ones would be potential future additions.

**Comment by jl-wynen** [comment]
I think that is all of them. Except last time I looked, commodity was still experimental.
