### ISSUE TITLE
[DataGroup] Advanced indexing

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2952]
We probably want to support [Advanced indexing](https://scipp.github.io/user-guide/slicing.html#Advanced-indexing) for `DataGroup`.

1. Decide on behavior, in particular in which cases we want to raise when shapes are inconsistent.
2. Implement.

**Comment by jl-wynen** [comment]
I would say we map the indexing operation over all items. If any fails, that makes the whole operation fail. This means that 
- boolean indexing: all items must have the same shape
- index list: all items must have a shape that is at least as large as the largest index in the list. It does not matter if items are larger. E.g. `DataGroup({'a': arange('x', 5), 'b': arange('x', 10)})['x', [2, 3]]` works fine because all items have a 2nd and 3rd element.

In general, the index (list or boolean array) determines the shape of the output (in the given dim). So as long as all inputs can be sliced down to that shape, it is fine.

**Comment by SimonHeybrock** [comment]
Sounds reasonable.
