### ISSUE TITLE
Cannot histogram integer count data

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#3126]
```Py
import scipp as sc
import numpy as np

N = 1000
counts = sc.ones(sizes={'event': N}, dtype=int, unit='counts')
tof = sc.array(dims=['event'], values=np.random.normal(size=N))
da = sc.DataArray(data=counts, coords={'tof': tof})
da.hist(tof=100)
```
fails with
![Screenshot at 2023-04-21 11-54-11](https://user-images.githubusercontent.com/39047984/233608083-1e089959-a537-4a6f-9b25-0a19e813eebb.png)

**Comment by SimonHeybrock** [comment]
See https://github.com/scipp/scipp/blob/789f237296a42e7e2cbe1d33a73adc1bc1e71eda/lib/core/include/scipp/core/element/histogram.h#L38-L60, apparently integer weights are not support, for no apparent reason. 

Take care when adding `int32` support, probably the output should be `int64`?

**Comment by SimonHeybrock** [comment]
> Take care when adding `int32` support, probably the output should be `int64`?

Actually, we don't that that for `sum()`, iirc, so keeping it `int32` may be fine? Not sure.

**Comment by SimonHeybrock** [comment]
You also need to change the output dtype, but otherwise, yes.

It will make it compile longer, yes, and increase the binary size (maybe you can check both, so we can get a feeling for the time and size?).

This is indeed a problem that we also have more generally. There are at least two potential solutions:

- Convert input dtypes to a smaller subset (e.g., the resulting output dtype) before the operation. Unless done on just internal buffers (inside transform) this could be a large overhead.
- Operate on the raw bytes (char arrays?) in cases where it does not matter. This is an option for `bin`, which just copies data, but not for `hist`, since it needs to accumulate.

In the case of `hist`, one could "factor" the operation into two stages, the comparison and the accumulation. This is the approach `bin` takes, and it would reduce the number of dtype combinations, since we will not need the combination of four dtypes any more. However, doing it in two stages is more costly. However, if we want to support 2-D (or higher) histogramming then this would anyway be a solution we will consider.

**Comment by SimonHeybrock** [comment]
I notice that in the current dtype listing there out `Out` types that do not match the input `Weight` types. I cannot remember why that is? Did we support `hist` with a user-provided `out` argument? If so, I think that is not the case any more? It would be worth checking of the list if types can thus be cleaned up, to something more manageable.
