### ISSUE TITLE
Unnecessary conversion of units

### ISSUE THREAD

**Issue by jfkcooper** [scipp/scipp#3181]
I was looking to see how to implement units for a project I'm working on, but am confused by the output of:
```
energy_kjmol = 1.0 *sc.Unit('kJ / mol')
print(energy_kjmol)
```
which for me at least gives `<scipp.Variable> ()    float64         [kW/kat]  1`

I think this may technically be correct since katal is mole per second, and Watt is Joule per second. But I am unable to get the unconverted unit e.g. in `kJ/mol` as I was expecting.

**Comment by SimonHeybrock** [comment]
Hi Jos!

Generally speaking, this is a known limitation (or design choice) of the units library Scipp is using (https://github.com/LLNL/units) --- its string conversion uses some heuristics to "guess" the most likely representation. Obviously this will frequently not correspond to what a user wants.

In a case like you example, one could imagine to simply store and keep the input formatting. However, such an approach falls apart once there is math involved that results in the unit (I believe [Pint](https://pint.readthedocs.io/en/stable/) takes a different approach: it never cancels any units, unless explicitly requested, which can also be user unfriendly).

That being said, I think I have three answers:

1. I believe in the particular example you gave the heuristics are actually wrong: I think `mol` should be favored over `kat`, since it is an SI base unit. I will open an upstream issue to see if this can be fixed.

2. A workaround to your problem is described in our docs in [Prioritizing-Units-in-String-Formatting](https://scipp.github.io/reference/units.html#Prioritizing-Units-in-String-Formatting), basically you can use, e.g., `sc.units.aliases['kJ/mol'] = 'kJ/mol'` to force/favor formatting of this unit. Note that this is a global approach, i.e., you cannot solve everything using this mechanism.

3. If you have any ideas for a better approach (combining advantages of the `llnl/units` and the `pint` approaches), I'd be really glad to hear them!

**Comment by SimonHeybrock** [comment]
The new upstream release 0.9.0 should fix this. We will update Scipp to use the new version soon.
