### ISSUE TITLE
``bin-edge`` label and alignment indication are missing for a selected bin.

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/scipp#3207]
In the cell `#2`, it the coordinate name has `[bin-edge]` mark but in the cell `#3`, `lat` coordinate doesn't have the `[bin-edge]` mark.

In the cell `#2`, the coordinate names are not `bold` not like other `bin-edges` in the call `#3`.

So far it was observed when a single bin is selected, and none of issues happens when the bin size is 1 when created, i.e. `da.bin(longi=1, lati=1)`

Code snippet to reproduce this issue is below the screen shot image.

![image](https://github.com/scipp/scipp/assets/17974113/8f5a513e-c50d-487f-ae78-3c585854df3b)

```
import scipp as sc
import numpy as np
rng = np.random.default_rng(123)
da = sc.DataArray(data=sc.ones(sizes={"row": 1000}, unit="counts"),
                  coords={'long': sc.array(dims=['row'], values=rng.random(1000)),
                          'lat': sc.array(dims=['row'], values=rng.random(1000)),
                          'time': sc.array(dims=['row'], values=rng.random(1000))})

da.bin(long=10, lat=10)['long', :2]['lat', 2]
```

**Comment by jokasimr** [comment]
I've started looking at this and I have some questions.

In the above example
* `lat` is not bolded because `da.coords['lat'].aligned` is `False`,
* `lat` does not have the `[bin-edges]` label because `'lat' in da.bin(long=10, lat=10)['long', :2]['lat', 2].dims` is `False`.

1. Is the bug that `da.coords['lat'].aligned` should be `True` or that `lat` should be bold despite `da.coords['lat'].aligned` being `False`?
2. Is the bug that `lat` is not contained in the `dims` attribute of the binned `DataArray` after slicing, or that `lat` should be displayed as a `[bin-edge]` coordinate despite not being present in the `dims` attribute?

**Comment by SimonHeybrock** [comment]
Also note the difference to the string-repr, which is correct, `print(da['x', 1])` yields:

```python
<scipp.DataArray>
Dimensions: Sizes[y:2, ]
Coordinates:
  x                           int64  [dimensionless]  (x [bin-edge])  [1, 2]
* y                           int64  [dimensionless]  (y [bin-edge])  [0, 1, 2]
Data:
                              int64  [dimensionless]  (y)  [2, 4]
```

**Comment by jokasimr** [comment]
Okay thanks!
