### ISSUE TITLE
Make `sc.concat` concatenate along unique existing dimension by default

### ISSUE THREAD

**Issue by jokasimr** [scipp/scipp#3446]
Example:

```python
sc.concat((sc.arange('x', 5), sc.arange('x', 5, 10)))
# raises missing argument
```
would be convenient to not have to specify the dimension again in the call to `concat`. That is, if `concat` assumed that since no `dim` argument was passed, the concatenation should happen along the only existing dimension `x`.

Alternatives:
1. Make this the default only if all arrays are 1D and share the dimension.
2. Make this the default if the arrays have a single shared dimension. That's a bit more magical, but maybe convenient.

**Comment by SimonHeybrock** [comment]
Since `concat` also supports concatenation along *new* dimensions I feel this is a confusing design. Very little is gained by being implicit, but it encourages unclear and error prone code that will break as soon as some input property changes. For example, we frequently write some code, only to notice later that the data will in practice have additional dimensions.

The suggested alternatives sound even more error prone?

Note that if you *know* that your inputs have only a single dim, you can use the `dim` property (singular) to heave nearly the same convenience:

```python
sc.concat(a1, a2, a1.dim)
```
