### ISSUE TITLE
Unexpected propagation of setting variances to ``Variable`` through ``DataArray``

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/scipp#3458]
Christian gave me a feedback about the tutorial of scipp
that the setting variances in the `DataArray` propagates all the way to the original `Variable`.

It was 
https://scipp.github.io/getting-started/quick-start.html
This page,

```python
array = array.copy()
array.variances = np.square(rng.random((4, 5)))
sc.show(array)
```
He tried deleting ``array = array.copy()``  in this part and found it out.

I agree that it can be surprising to users.
Should we add the explanation whenever we have `copy` in the tutorial?

Or can we make it in a way that setting variances on `DataArray` doesn't affect the original `Variable` that became the `DataArray.data`?

**Comment by nvaytet** [comment]
> Or can we make it in a way that setting variances on DataArray doesn't affect the original Variable that became the DataArray.data?

I don't think we can do that because of the shared ownership mechanism. Without it, you would be making copies of variables every time we insert them into a `DataArray`. We used to have something like that in the past, but we decided a while ago now that `DataArray` and `Dataset` should behave like python dicts.

If you add the same numpy array to 2 different python dicts, they point to the same object. If you modify the array values in-place, it will be modifies in both dicts.

> Should we add the explanation whenever we have copy in the tutorial?

We could. Maybe the best would be to have a page explaining the shared ownership mechanism, and link to that when we make use of `copy`? I think we haven't really so far because we thought "well that's just how python works".
But it is probably not obvious to everyone who starts using Scipp & co.

**Comment by SimonHeybrock** [comment]
> Maybe the best would be to have a page explaining the shared ownership mechanism, and link to that when we make use of `copy`? I think we haven't really so far because we thought "well that's just how python works".
> But it is probably not obvious to everyone who starts using Scipp & co.

https://scipp.github.io/reference/ownership-mechanism-and-readonly-flags.html?

**Comment by SimonHeybrock** [comment]
Did you want to do more here (add more links to that page?), or should this be closed?

**Comment by YooSunYoung** [comment]
> Did you want to do more here (add more links to that page?)
I'll do that.
