### ISSUE TITLE
Dataset sort 

### ISSUE THREAD

**Issue by igudich** [scipp/scipp#393]
Implement `sort`.

See https://github.com/scipp/scipp/tree/v0.0.1 and in particular dataset.h (before the refactor) for what was previously supported.

**Comment by SimonHeybrock** [comment]
The main application of this is for sorting tables, and for sorting sparse data. For the sparse data case see #358.

**Comment by SimonHeybrock** [comment]
Decided to remove this from the release, since there are many things to consider, making this too large a task, given that it is not urgently required. Concrete things to solve are:

- How do we refer to a "column" when sorting. Just using the `Dim` key to select a coord is not sufficient. May often want to sort by labels or data. One solution would get something like `dataset = sort(dataset, dataset.labels["aux"]).
- What if the sort key has variances?
- Should we support sorting by variances?
- Should multi-dimensional data be supported, and to what extent? Multi-dimensional sort keys?
- Sorting sparse data and how it combines with sorting dense data.
