### ISSUE TITLE
Brainstorming: Collaboration opportunities with xarray

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#500]
> @SimonHeybrock very cool to see your Scipp project! I will make some comments over in your repo but I'm impressed with what you've done. I'd love to find ways to collaborate more in the future, many of the problems you're solving are also important for xarray users.

@shoyer thank you very much for you interest! I thought I'd take the opportunity to throw some items for discussion into the room, to get a conversation started.

Right now, the following come to my mind:

- Dask support.
- I/O.
- Jupyter visualizations.
- Plotting.

**Comment by nvaytet** [comment]
`scipp` and `xarray` datasets are now so similar that it could be possible to have a plotting package using `plotly` that can take in both types of datasets with minimal amount of `if` statements.

Could be separate from `scipp-core` (`scipp-plot`?) it would also fit well with `xarray` since they don’t have `plotly`, just `matplotlib`.

There is `hvplot` that can plot `xarray` datasets but they use `bokeh` and `holoviews`. They do however use `plotly` for 3D plots. `scipp-plot` could be an alternative if you wanted to use `plotly` across the board, from 1 to 3 dimensions.
