### ISSUE TITLE
Mantid Workspace -> DataArray converters: monitors

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#615]
At this point the converters do not handle monitors, unless they are normal spectra. The following changes have to be made:

1. We should (usually?) *NOT* store monitors as normal spectra. The way Mantid handles this is to have a special `isMonitor` flag for each detector/spectrum, and Algorithms then have to check whether a histogram or event list is a monitor and adapt their behavior. I belive this is not a good or viable solution for a general-purpose library like scipp.
2. Exclude monitors when converting workspaces, i.e., some of the spectra in the Mantid workspace would not be part of the data in the ouput `DataArray`.
3. Store monitors in another way. The main options are to use labels or attributes. Labels would prevent operations between data with different monitor values, which may be required in some cases. However, using attributes appears to be the better and more generic choice for now (of course client code can always change this afterwards, if required).

- To support different types of monitors (e.g., histogram and event) we should probably use a different 0-D attribute for each monitor (each monitor could be pixellated internally). Typically each monitor would be a `DataArray`, which could contain a histogram or events.
- Need to look into other way Mantid stores monitors (e.g., via a link to a "monitor workspace"), and convert that data.

**Comment by SimonHeybrock** [comment]
One thing we should keep in mind is how to handle unit conversions for monitors. Mantid has special-case handling for this (both in `DetectorInfo` for computing `L_2` as well as in `ConvertUnits`). Obviously we cannot do this, so we a different way of converting units for monitors, maybe via a dedicated function.

**Comment by OwenArnold** [comment]
1. We may need to consider the case that the monitors may start as a normal spectra rather than something that can be easily pre-defined based on some Geometry label (as in Nexus Format). For example, you want to treat arbitrary regions of the detector surface as your monitor. This is a frequent operation in Large Scale Structures (SANS, REFL). This region would typically be determined as part of the data reduction. See for example `IOMonitorIndex` passed via Algorithm property. But as far as you say, knowing beforehand that you have a monitor you are probably in the position to separate it away from the data into another storage category label/attribute.

2. I had considered storage as follows, but I think that the potential for accidental operation is too high. Most of the time you would NOT want to sum monitor counts and this would be better handled by storing the counts of the monitor themselves as labels/attributes since you can still explicitly add monitor counts, but would not usually wish to do so.
```
ds = Dataset()
ds["counts"] = Variable([Dim.Spectrum, Dim.Tof], values=np.arange(200).reshape(10, 20))
ds.labels["is_monitor"] = Variable([Dim.Spectrum], values=np.ones(10, dtype=bool))
```

3. I have a preference for Labels given that there are pitfalls for operations between datasets where the monitors stored as attributes should match but do not for example may be difficult to trace the source of the problems for example. Would be useful to know what operations you had in mind that would make labels unsuitable? Maybe a scaling operation though I don't see how that would propagate through to labels other than by willfully applied.

```To support different types of monitors (e.g., histogram and event) we should probably use a different 0-D attribute for each monitor (each monitor could be pixellated internally). Typically each monitor would be a DataArray, which could contain a histogram or events.```

If you mean that we need to consider things like different TOF ranges and steps for monitors I agree. Monitors TOF range may be quite different than for the detector data. Prior to say division, a rebin of course would need to be provided, but for treatment of monitors it may not make sense to do this early:

```
ds = Dataset()
ds["counts"] = Variable([Dim.Spectrum, Dim.Tof], values=np.arange(200, dtype=np.float64).reshape(10, 20))
da = DataArray(data=Variable([Dim.Tof], values=np.arange(50)), coords={Dim.Tof: Variable([Dim.Tof], values=np.arange(50,100))})
ds.attrs["monitors"] = Variable(value=da)
```
Though how best to then proceed to something equivalent to:

```
ds["counts"]/ds.attrs["monitors"]
```

Linked monitor workspaces simply allow for EventWorkspace -> Workspace2D linking or similar handling where the loading might be a two step process.

As far as unit conversion is concerned, we would need to identify that the label/attribute is a monitor (we can possibly only do this via some naming convention), but we can then apply the special case that the sample does not feature in the flight path as part of unit conversion.

**Comment by SimonHeybrock** [comment]
>     1. We may need to consider the case that the monitors may start as a normal spectra rather than something that can be easily pre-defined based on some Geometry label (as in Nexus Format). For example, you want to treat arbitrary regions of the detector surface as your monitor. This is a frequent operation in Large Scale Structures (SANS, REFL). This region would typically be determined as part of the data reduction. See for example `IOMonitorIndex` passed via Algorithm property. But as far as you say, knowing beforehand that you have a monitor you are probably in the position to separate it away from the data into another storage category label/attribute.

Maybe it makes more sense to speak about this as "normalization to straight beam area" rather than monitors.

>     2. I had considered storage as follows, but I think that the potential for accidental operation is too high. Most of the time you would NOT want to sum monitor counts and this would be better handled by storing the counts of the monitor themselves as labels/attributes since you can still explicitly add monitor counts, but would not usually wish to do so.
> 
> 
> ```
> ds = Dataset()
> ds["counts"] = Variable([Dim.Spectrum, Dim.Tof], values=np.arange(200).reshape(10, 20))
> ds.labels["is_monitor"] = Variable([Dim.Spectrum], values=np.ones(10, dtype=bool))
> ```

I think Mantid's `isMonitor` is not so useful in general. I see little need for it if we just store monitors as attributes and address them by their name when needed.

>     3. I have a preference for Labels given that there are pitfalls for operations between datasets where the monitors stored as attributes should match but do not for example may be difficult to trace the source of the problems for example. Would be useful to know what operations you had in mind that would make labels unsuitable? Maybe a scaling operation though I don't see how that would propagate through to labels other than by willfully applied.

If monitors are labels you, e.g., cannot normalize to vanadium without first removing the monitors. The same goes for background subtraction.

To justify monitors as labels, I would ask the other way round: Are there real cases where the monitors are the same for two operands in an operation? I cannot think of any, so monitors as labels would just serve to prevent all binary operations.


> >To support different types of monitors (e.g., histogram and event) we should probably use a different 0-D attribute for each monitor (each monitor could be pixellated internally). Typically each monitor would be a DataArray, which could contain a histogram or events.`
> 
> If you mean that we need to consider things like different TOF ranges and steps for monitors I agree. Monitors TOF range may be quite different than for the detector data. Prior to say division, a rebin of course would need to be provided, but for treatment of monitors it may not make sense to do this early:
> 
> ```
> ds = Dataset()
> ds["counts"] = Variable([Dim.Spectrum, Dim.Tof], values=np.arange(200, dtype=np.float64).reshape(10, 20))
> da = DataArray(data=Variable([Dim.Tof], values=np.arange(50)), coords={Dim.Tof: Variable([Dim.Tof], values=np.arange(50,100))})
> ds.attrs["monitors"] = Variable(value=da)
> ```
> 
> Though how best to then proceed to something equivalent to:
> 
> ```
> ds["counts"]/ds.attrs["monitors"]
> ```

```python
ds /= sc.rebin(ds.attrs['transmission_monitor'], Dim.Tof, ds.coord[Dim.Tof])
```

> Linked monitor workspaces simply allow for EventWorkspace -> Workspace2D linking or similar handling where the loading might be a two step process.

This is handled by having the monitors as nested `DataArray`:

```python
ds /= sc.histogram(ds.attrs['transmission_monitor'], ds.coord[Dim.Tof])
```

> As far as unit conversion is concerned, we would need to identify that the label/attribute is a monitor (we can possibly only do this via some naming convention), but we can then apply the special case that the sample does not feature in the flight path as part of unit conversion.

I disagree here. There is no generic way to identify which attribute is a monitor, and if so whether it should be converted or not. As soon as we introduce more complex geometry (mirrors, multiple incident angles, ...) this just becomes intractable and hard to reasons about. I think this should be handled explicitly by a special function call and *NOT* magically inside the existing `convert`. `convert` is "defined" to change coordinates and dimensions, not anything else.

**Comment by OwenArnold** [comment]
>> If monitors are labels you, e.g., cannot normalize to vanadium without first removing the monitors. The same goes for background subtraction.

Yes any scaling operation you illustrate Lorentz correction etc could cause these problems. I think this is good justification to prefer attributes

>> As far as unit conversion is concerned, we would need to identify that the label/attribute is a monitor (we can possibly only do this via some naming convention), but we can then apply the special case that the sample does not feature in the flight path as part of unit conversion.

> I disagree here. There is no generic way to identify which attribute is a monitor, and if so whether it should be converted or not. As soon as we introduce more complex geometry (mirrors, multiple incident angles, ...) this just becomes intractable and hard to reasons about. I think this should be handled explicitly by a special function call and NOT magically inside the existing convert. convert is "defined" to change coordinates and dimensions, not anything else.

This would indeed probably be better. I dislike relying on naming for anything if possible, and we should stay reasonably save since any attempt to operate between unit converted detector data (say to wavelength) and the monitor data (which is not automatically converted so say remains in TOF), will result in operation failure.
