### ISSUE TITLE
Plot data not sharing axis in same plot?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#802]
Users asked for plotting data with different axis (different values and range, but some dimension) in the same plot (I believe only 1-D plots where meant). As far as I can tell this is not possible right now.

Would this be easy to add?

**Comment by nvaytet** [comment]
This can be achieved using the `mpl_axes` keyword argument, see https://scipp.readthedocs.io/en/latest/visualization/customizing-figures.html#Placing-figures-inside-existing-Matplotlib-axes

A 1D example:
```Py
import numpy as np
import scipp as sc
from scipp import Dim
from scipp.plot import plot
```
```Py
d1 = sc.Dataset()
N = 50
d1.coords[Dim.Tof] = sc.Variable([Dim.Tof], values=np.arange(N).astype(np.float64) + 20.0,
                                 unit=sc.units.us)
d1['Sample1'] = sc.Variable([Dim.Tof], values=10.0*np.random.rand(N),
                           unit=sc.units.counts)
d2 = sc.Dataset()
M = 100
d2.coords[Dim.Tof] = sc.Variable([Dim.Tof], values=np.arange(M).astype(np.float64),
                                 unit=sc.units.us)
d2['Sample2'] = sc.Variable([Dim.Tof], values=2.0*np.random.rand(M),
                            unit=sc.units.counts)
```
```Py
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1, figsize=(9, 6))
plot(d1["Sample1"], mpl_axes=ax)
plot(d2["Sample2"], mpl_axes=ax, color=1)
ax.set_ylim([0, 10])
fig
```
yields
![Screenshot at 2020-01-07 14-05-25](https://user-images.githubusercontent.com/39047984/71898557-ef9b3c80-3159-11ea-93d1-55caa6541e15.png)

**Comment by SimonHeybrock** [comment]
Would it make sense to just add an FAQ entry for this (maybe just give the 5 lines of code, then link to the full relevant documentation)?

**Comment by nvaytet** [comment]
Before the break I was actually looking to see if Github also provided a forum platform where people could ask questions, without having to open issues, as it may not be an issue at all, just needing to know how to use a function.

I couldn't really find anything on Github. Seems you have to go third party solutions. There is of course Discourse, but it's a little annoying to have to go elsewhere again: Github, Readthedocs, Discourse... but then I guess these 3 are pretty standard for many other projects these days.

I don't like Gitter so much because it's just one long stream of messages and it's impossible to keep track of discussions on a particular topic.

**Comment by nvaytet** [comment]
@celinedurniak did this solve your problem? Or do you require additional functionality to be implemented in the `plot` function?

**Comment by SimonHeybrock** [comment]
Assuming this is solved, please open a new issue if not.
