### ISSUE TITLE
Substitute UTF-8 symbols from  style.css with their ascii representation.

### ISSUE THREAD

**Issue by igudich** [scipp/scipp#904]
Remove UTF-8 symbols from https://github.com/scipp/scipp/blob/master/python/src/scipp/table_html/style.css. To avoid breaking scipp import on system where locale is not set (server or container).

← -->&larr
for example.

**Comment by DanNixon** [comment]
I'd advise against this. We actually want those symbols as they are used in the Jupyter Notebook rendering.

Rather, this issue is not having a locale set (or at least on that supports UTF-8).
You can remedy this by setting the locale to something like `C.UTF-8` (for a geographically agnostic choice).

**Comment by SimonHeybrock** [comment]
@DanNixon I don't think this is about removing the UTF8 symbols from the output, but rather using a different encoding such as `&#x3bc;` (instead of putting actual unicode characters in the text file). Isn't that possible? I had hoped that would fix the issue.

**Comment by DanNixon** [comment]
> Isn't that possible? I had hoped that would fix the issue.

Yes, and it would get rid of this issue. However I still stick to what I said earlier because:
- It makes the developers life harder when they do not see the actual character
- The actual issue is a locale misconfiguration
- One could argue that we shouldn't actually be importing visualisation modules so early (this may or may not be relevant, I'm not sure how this was being used)

(yes, I am going to call a nonm-utf8 locale a misconfiguration, this will likely break more than just scipp nowadays and it takes specific or legacy hardware to prevent unicode from being supported)

**Comment by nvaytet** [comment]
I would also rather have encoding as `&#x3bc;` instead of having the actual character in the source file.

**Comment by DanNixon** [comment]
> I would also rather have encoding as `&#x3bc;` instead of having the actual character in the source file.

Why? So that you are forced to do a lookup to read it (rather than only when changing it)?

**Comment by nvaytet** [comment]
Even if it is a locale misconfiguration, you might not always have the rights to modify it yourself, and asking a sysadmin to change it just for two characters seems rather a lot, especially since there is a very simple fix for this.

I agree that it might "break more than just scipp nowadays", but that might be the problem of the other packages that break. At least `scipp` would not break because of that.

**Comment by DanNixon** [comment]
> Even if it is a locale misconfiguration, you might not always have the rights to modify it yourself

Yes, you do. Locale is a user specific setting.

**Comment by nvaytet** [comment]
It is not difficult for a developer to just go and look up the menaing of the symbol but is difficult for a user to fix this if they are non-expert. This just adds another potential reason for someone not to use `scipp` because they can't import it.

**Comment by DanNixon** [comment]
Fine. I've reached my limit of caring about this.

**Comment by SimonHeybrock** [comment]
Closing, due to mixed optinions and no current trouble in practice.
