### ISSUE TITLE
Try live-data handling with scipp

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#932]
After discussion with @nvaytet, it appears relatively straightforward to handle live data + updates in a Jupyter notebook (modulo all the unknown issues):

- Use Mantid `StartLiveData` to connect to stream.
- Configure (post)processing step in `StartLiveData` to update a variable or trigger and event.
- Connect reduction and visualization to the event, using `ipywidgets`.

**Comment by nvaytet** [comment]
I've spoken to Torben about this, as he already has a demo with Mantid doing live streaming (and analysis) in a notebook

**Comment by matthew-d-jones** [comment]
The problem with the approach of using Mantid for this is that plots in the notebook cannot be updated during consumption of data. I have added a notebook to `ess-notebooks` to demonstrate this https://github.com/scipp/ess-notebooks/pull/7

I will continue by directly populating scipp data structures instead of using Mantid: #1448
